# SPDX-FileCopyrightText: Copyright Â© 2025 The Dymes project authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: dymes
description: Dymes Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: "0.0.0"
